In [1]:
# Advantages of using NumPy

# Create NumPy arrays
# Convert lists and tuples to NumPy arrays,
# Inspect the structure and content of arrays, and
# Subset, slice, index and iterate through arrays.

#### NumPy VS List

In [1]:
heights = [74, 75, 72, 72, 71]

In [2]:
heights

[74, 75, 72, 72, 71]

In [5]:
heights * 2.5  #can't multiply sequence by non-int of type 'float'

TypeError: can't multiply sequence by non-int of type 'float'

In [6]:
import numpy as np

In [7]:
np_heights = np.array([74, 75, 72, 72, 71])

In [8]:
np_heights

array([74, 75, 72, 72, 71])

In [9]:
type(np_heights)

numpy.ndarray

In [12]:
np_heights * 2.54

array([187.96, 190.5 , 182.88, 182.88, 180.34])

#### NumPy comes with it's own set of methods and operations

In [14]:
list_1 = [1, 2, 3]
list_2 = [4, 5, 6]
list_1 + list_2

[1, 2, 3, 4, 5, 6]

In [17]:
np1 = np.array([1, 2, 3])
np2 = np.array([4, 5, 6])
np1 + np2

array([5, 7, 9])

#### Working with N-D Array

In [19]:
np_heights

array([74, 75, 72, 72, 71])

In [20]:
type(np_heights)

numpy.ndarray

In [1]:
array_1 = [1,2,3,5,4,6,7,8,5,3,2]

In [2]:
print(array_1[:3])

[1, 2, 3]


In [3]:
array_1 = [1,2,3,5,4,6,7,8,5,3,2]

In [4]:
print(array_1[2:-3])

[3, 5, 4, 6, 7, 8]


In [5]:
array_1 = [1,2,3,5,4,6,7,8,5,3,2]

In [6]:
print(array_1[ : : -2])

[2, 5, 7, 4, 3, 1]


In [8]:
input_list = [ 1, 5, 9, 12, 15, 7, 12, 9 ]
m = 6
n = 12

In [10]:
import numpy as np

In [11]:
array_1 = np.array(input_list)

In [17]:
array_2 = array_1 [ array_1 > m]

In [19]:
final_array = array_2 [ array_2 < n]

In [20]:
final_array

array([9, 7, 9])