In [1]:
# Week 1 : # int, bool, float, string

In [2]:
# Week 2 : # list, tuple, sets, dict

In [3]:
# Week 2 : # for while if else break continue pass

In [4]:
# Week 3 : # lambda map reduce filter || hands-on

In [5]:
# Week 4 Day 1 : # numpy --> arrays

In [6]:
# Week 4 Day 2 : #pandas --> Series, DataFrame!

# What is Pandas?

Pandas is one of the most important libraries of Python.
</br>
Pandas has data structures for data analysis. The most used of these are Series and DataFrame data structures. Series is one dimensional, that is, it consists of a column. Data frame is two-dimensional, i.e. it consists of rows and columns.

To install Pandas, you can use "pip install pandas"

In [11]:
# pip install pandas

In [12]:
import numpy  as np
import pandas as pd

In [15]:
np.__version__

'1.22.4'

In [16]:
pd.__version__

'2.2.2'

# Series Data Structure

A Pandas Series is like a column in a table. It is a one-dimensional array holding data of any type.

In [17]:
obj = pd.Series([1,"John",3.5,"Hey"])
obj

0       1
1    John
2     3.5
3     Hey
dtype: object

In [19]:
# column in a table
# index
# datatype!

In [20]:
type(obj)

pandas.core.series.Series

In [23]:
obj.dtype

dtype('O')

In [24]:
obj

0       1
1    John
2     3.5
3     Hey
dtype: object

In [25]:
obj[:3] #0,1,2 index!

0       1
1    John
2     3.5
dtype: object

In [26]:
obj

0       1
1    John
2     3.5
3     Hey
dtype: object

In [27]:
obj.values

array([1, 'John', 3.5, 'Hey'], dtype=object)

In [28]:
type(obj.values)

numpy.ndarray

In [29]:
# series is a 1d array!

In [30]:
obj2 = pd.Series([1,"John",3.5,"Hey"],
                 index=["a","b","c","d"])
obj2

a       1
b    John
c     3.5
d     Hey
dtype: object

In [31]:
obj2["b"]

'John'

In [32]:
obj2.values

array([1, 'John', 3.5, 'Hey'], dtype=object)

In [33]:
obj2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [34]:
score={"Jane":69, "Bill":80,
       "Elon":85,"Tom":75,"Tim":95}

type(score)

dict

In [35]:
print(score)

{'Jane': 69, 'Bill': 80, 'Elon': 85, 'Tom': 75, 'Tim': 95}


In [37]:
names=pd.Series(score) # Convert to Series 
names
# keys   : index
# values : values

Jane    69
Bill    80
Elon    85
Tom     75
Tim     95
dtype: int64

In [40]:
# names['elon'] #python is a case sensitive language!

In [41]:
names['Elon']

85

In [44]:
names['Tim']

95

In [45]:
names.index

Index(['Jane', 'Bill', 'Elon', 'Tom', 'Tim'], dtype='object')

In [46]:
names.values

array([69, 80, 85, 75, 95])

In [47]:
20 > 10

True

In [48]:
20 < 10

False

In [49]:
names

Jane    69
Bill    80
Elon    85
Tom     75
Tim     95
dtype: int64

In [51]:
names >= 85

Jane    False
Bill    False
Elon     True
Tom     False
Tim      True
dtype: bool

In [52]:
names[names>=85]

Elon    85
Tim     95
dtype: int64