In [1]:
import numpy  as np
# import pandas as pd -- tomorrow

### Create an array from an iterable
Such as
- ```list```
- ```tuple```
- ```range``` iterator

Notice that not all iterables can be used to create a numpy array, such as ```set``` and ```dict```

In [2]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [3]:
type(arr)

numpy.ndarray

In [4]:
arr.dtype

dtype('int64')

In [5]:
arr = np.array((1,2,3,4,5))
print(arr)
# () = tuple

[1 2 3 4 5]


In [6]:
type(arr)

numpy.ndarray

In [7]:
arr = np.array(range(2,10))
print(arr)

[2 3 4 5 6 7 8 9]


In [8]:
arr = np.array(range(10))
print(arr)

[0 1 2 3 4 5 6 7 8 9]


### Create an array with specified data type

In [9]:
arr1 = np.array(range(10))
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
arr1.ndim
# dimensions of the array

1

In [11]:
arr = np.array([[1,2,3], [4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [12]:
arr.ndim

2

In [15]:
ar = np.array([[[1,2,3]]])
print(ar)

[[[1 2 3]]]


In [16]:
ar.ndim

3

### Create an aray within specified range
```np.arange()``` method can be used to replace ```np.array(range())``` method

In [17]:
# np.arange(start, stop, step)
arr = np.arange(0,20,2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [18]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

### Create an array of evenly spaced numbers within specified range


In [19]:
# start - 0, end - 10, no.of elem - 3
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [20]:
# 5-0  = 5
# 10-5 = 5

In [21]:
np.linspace(0,10,7)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

In [22]:
3.33333333-1.66666667

1.66666666

In [23]:
5.-3.33333333

1.6666666700000001

In [28]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [30]:
np.linspace(0,10,3,endpoint=False)

array([0.        , 3.33333333, 6.66666667])

In [32]:
np.linspace(0,10,3,endpoint=False).round(2)

array([0.  , 3.33, 6.67])