In [1]:
import numpy  as np

### Create an array of random values of given shape
```np.random.rand()``` method returns values in the range [0,1)

In [2]:
arr = np.random.rand(3,2)
# rows,columns
print(arr)
# (0,1]

[[0.0275881  0.17904893]
 [0.4821877  0.43843156]
 [0.05900466 0.34778521]]


In [3]:
arr.shape #rows,columns

(3, 2)

In [6]:
np.random.uniform(1,7,(4,4))
# 4,4 array whose elements will 
# be between 1 and 7

array([[6.27130771, 3.60080857, 3.75295795, 3.25739687],
       [6.34205236, 5.24874855, 2.44419845, 4.1484326 ],
       [3.94126756, 5.55726964, 2.09890353, 4.38150412],
       [3.85205903, 5.31651202, 1.84793436, 1.27899836]])

In [7]:
np.random.uniform(0.1,0.2,(4,4))


array([[0.13143633, 0.10969083, 0.19625197, 0.19241145],
       [0.14280145, 0.17872947, 0.19802657, 0.1050732 ],
       [0.17756615, 0.12837996, 0.11748408, 0.17314985],
       [0.13357208, 0.15386394, 0.12546947, 0.10495948]])

### Create an array of zeros of given shape 
- ```np.zeros()```: create array of all zeros in given shape


In [8]:
zeros = np.zeros((3,2))
print(zeros)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [9]:
ones = np.ones((3,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### Create an array of constant values of given shape  
- ```np.full()```: create array of constant values in given shape


In [12]:
full = np.full((4,2), 105)
print(full)

[[105 105]
 [105 105]
 [105 105]
 [105 105]]


### Create an identity matrix of given size


In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])