In [1]:
import numpy as np

In [2]:
arr = np.random.rand(2,2).round(2)
arr

array([[0.72, 0.82],
       [0.84, 0.19]])

### element-wise addition, subtraction, multiplication and division

In [3]:
arr

array([[0.72, 0.82],
       [0.84, 0.19]])

In [4]:
print(arr + 10)

[[10.72 10.82]
 [10.84 10.19]]


In [5]:
print(arr - 10)

[[-9.28 -9.18]
 [-9.16 -9.81]]


In [6]:
arr

array([[0.72, 0.82],
       [0.84, 0.19]])

In [7]:
print(arr * 10)

[[7.2 8.2]
 [8.4 1.9]]


In [8]:
print(arr / 10)

[[0.072 0.082]
 [0.084 0.019]]


In [9]:
arr

array([[0.72, 0.82],
       [0.84, 0.19]])

In [10]:
np.max(arr)

0.84

In [11]:
np.min(arr)

0.19

In [12]:
np.mean(arr)

0.6425

In [13]:
np.sqrt(arr)

array([[0.84852814, 0.90553851],
       [0.91651514, 0.43588989]])

In [14]:
np.log(arr)

array([[-0.32850407, -0.19845094],
       [-0.17435339, -1.66073121]])

In [15]:
arr

array([[0.72, 0.82],
       [0.84, 0.19]])

In [16]:
np.sum(arr)

2.57

### sum along a specified axis

In [ ]:
# Axis = 0 #rows
# Axis = 1 #columns

In [ ]:
# axis 1 - sideways
# axis 0 - downwards

In [18]:
arr

array([[0.72, 0.82],
       [0.84, 0.19]])

In [19]:
np.sum(arr, axis=1)

array([1.54, 1.03])

In [20]:
np.sum(arr, axis=0)

array([1.56, 1.01])

### compute the min and max along a specified axis

In [21]:
arr 

array([[0.72, 0.82],
       [0.84, 0.19]])

In [22]:
# 1) 
print(np.min(arr, axis=0))

[0.72 0.19]


In [23]:
# 2)
print(np.min(arr, axis=1))

[0.72 0.19]


In [24]:
# 3)
print(np.max(arr, axis=1))

[0.82 0.84]


In [25]:
# 4)
print(np.max(arr))

0.84


In [26]:
# 5)
print(np.min(arr))

0.19


## compute the mean

In [27]:
arr

array([[0.72, 0.82],
       [0.84, 0.19]])

In [28]:
# 1)
print(np.mean(arr))

0.6425


In [29]:
# 2)
print(np.mean(arr, axis=0))   

[0.78  0.505]


In [30]:
# 3)
print(np.mean(arr, axis=1)) 

[0.77  0.515]


# Sort

In [31]:
arr = np.random.rand(3,3).round(2)
arr

array([[0.76, 0.8 , 0.16],
       [0.78, 0.84, 0.34],
       [0.66, 0.74, 0.88]])

In [32]:
# sort along the row in place
arr.sort(axis=0)
print(arr)

[[0.66 0.74 0.16]
 [0.76 0.8  0.34]
 [0.78 0.84 0.88]]


In [33]:
# sort along the column in place
arr.sort(axis=1)    
print(arr)

[[0.16 0.66 0.74]
 [0.34 0.76 0.8 ]
 [0.78 0.84 0.88]]
