In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6])

In [4]:
arr[0]

1

In [5]:
arr[:2]
# 0th and 1st index in the output!

array([1, 2])

In [7]:
arr[:2][0]

1

In [8]:
arr = np.array(range(9)).reshape((3,3))

In [9]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
arr.ndim

2

In [11]:
arr[0]

array([0, 1, 2])

In [12]:
arr[0][-2]

1

### indexing with slicing

In [13]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
arr[1]

array([3, 4, 5])

In [16]:
#       0 1 2
    
# 0 --> 0 1 2
# 1 --> 3 4 5 
# 2 --> 6 7 8

In [17]:
arr[1,1]
# rows,columns

4

In [18]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
arr[:3,:2]

array([[0, 1],
       [3, 4],
       [6, 7]])