In [1]:
import numpy as np

In [2]:
arr = np.random.rand(3,2).round(2)
arr
# (3rows,2columns)

array([[0.4 , 0.96],
       [0.26, 0.03],
       [0.21, 0.58]])

In [3]:
arr.shape

(3, 2)

In [5]:
# Transpose --> rows -> column | column -> rows

In [6]:
arr.T

array([[0.4 , 0.26, 0.21],
       [0.96, 0.03, 0.58]])

### flatten an array

In [7]:
arr

array([[0.4 , 0.96],
       [0.26, 0.03],
       [0.21, 0.58]])

In [8]:
arr.flatten()

array([0.4 , 0.96, 0.26, 0.03, 0.21, 0.58])

### append elements to an array

In [10]:
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [11]:
np.append(arr, 10)

array([ 1,  2,  3, 10])

### insert elements into an array

In [12]:
arr

array([1, 2, 3])

In [13]:
arr3 = np.insert(arr, 0, 10)    
print(arr3)

[10  1  2  3]


### delete elements from an array

In [14]:
arr

array([1, 2, 3])

In [15]:
arr4 = np.delete(arr, 0)    
print(arr4)

[2 3]


In [27]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
np.delete(arr,0,axis=1)

array([[2, 3],
       [5, 6],
       [8, 9]])

In [29]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
np.delete(arr,0, axis=0)

array([[4, 5, 6],
       [7, 8, 9]])

In [20]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
np.delete(arr,0)
# flatten and remove first element

array([2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
a1 = np.array([[1,2,3],[4,5,6]])
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
new = np.array([7,8,9])
new

array([7, 8, 9])

In [25]:
# Q1:
np.insert(a1,0,new,axis=1)
# work - yes/no
# yes - output, no - reason?

ValueError: could not broadcast input array from shape (3,1) into shape (2,1)

In [26]:
# Q2:
np.insert(a1,0,new,axis=0)
# work - yes/no
# yes - output, no - reason?

array([[7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]])