In [1]:
import numpy as np

In [2]:
# Create a random array for demonstration
array_1 = np.random.rand(3,2).round(2)
array_1

array([[0.28, 0.42],
       [0.16, 1.  ],
       [0.75, 0.59]])

In [4]:
array_1.shape

(3, 2)

In [5]:
array_1.size

6

In [6]:
# 3,2 --> 4,2? NO
# 3,2 --> 2,3? YES
# 3,2 --> 6,1? YES
# 3,2 --> 1,6? YES

In [7]:
array_1

array([[0.28, 0.42],
       [0.16, 1.  ],
       [0.75, 0.59]])

In [9]:
# array_1.reshape(2,3)
array_1.reshape(1,6)

array([[0.28, 0.42, 0.16, 1.  , 0.75, 0.59]])

In [10]:
array_1.reshape(6,1)

array([[0.28],
       [0.42],
       [0.16],
       [1.  ],
       [0.75],
       [0.59]])

In [14]:
flat_arr = array_1.flatten()
flat_arr

array([0.28, 0.42, 0.16, 1.  , 0.75, 0.59])

In [15]:
np.argmax(flat_arr) 
# Index of the maximum value

3

In [16]:
np.argmin(flat_arr)
# Index of the minimum value

2

In [ ]:
# NaN --> Not a Number (Missing Values!)

In [17]:
# Handling np.nan
array_with_nan = np.array([1, 2, np.nan, 4, 5])  # Creating an array with a NaN value
array_with_nan

array([ 1.,  2., nan,  4.,  5.])

In [18]:
np.mean(array_with_nan)

nan

In [19]:
array_with_nan

array([ 1.,  2., nan,  4.,  5.])

In [20]:
np.nanmean(array_with_nan)  # Mean calculation ignoring NaN

3.0

In [21]:
(1+2+4+5)/4

3.0